require "rspec/openapi"

RSpec::OpenAPI.path = "swagger/openapi.yaml"
RSpec::OpenAPI.title = "Medical Information System API"
RSpec::OpenAPI.application_version = "1.0.0"
RSpec::OpenAPI.servers = [ { url: "http://localhost:3000" } ]
RSpec::OpenAPI.example_types = %i[ request ]
RSpec::OpenAPI.formats_builder = lambda do |_example, key|
  key.to_s.end_with?("_at") ? "date-time" : nil
end
RSpec::OpenAPI.comment = <<~COMMENT
  This file is generated by rspec-openapi.
  Run `OPENAPI=1 bin/rspec spec/requests` to update it from request specs.
COMMENT
